name: "新功能建议"
description: "为这个项目提出一个主意"
labels: "✦ 建议"

body:
- type: textarea
  id: feature
  attributes:
    label: 你希望增加什么功能？请简明描述
    placeholder: "请详细描述你需要的新功能或改进。"
  validations:
    required: true
- type: textarea
  id: scenario
  attributes:
    label: 使用场景
    placeholder: "请说明你希望在哪些场景下使用该功能，为什么这个功能对你有帮助。"
  validations:
    required: false
- type: textarea
  id: alternatives
  attributes:
    label: 你考虑过的替代方案
    placeholder: "如果有，请描述你尝试过或考虑过的其他解决方式。"
  validations:
    required: false
- type: textarea
  id: etc
  attributes:
    label: 其他信息
    placeholder: "你还想补充什么？比如相关截图、参考链接等。"
  validations:
    required: false
- type: checkboxes
  id: checklist
  attributes:
    label: 检查单
    description: "请逐项确认以下内容："
    options:
      - label: "我已将启动器更新至最新版，并且该建议依然适用。"
        required: true
      - label: "我确认没有人在 Issue 区提出过类似建议。"
        required: true
